volumes:
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      device: /home/aghla/data/mariadb
      o: bind
      type: none
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      device: /home/aghla/data/wordpress
      o: bind
      type: none

networks:
  main_net:
      name: main_net

services:
  mariadb:
    image: mariadb:1.3.3.7
    container_name: mariadb
    build: ./requirements/mariadb
    volumes:
      - mariadb:/var/lib/mysql
    env_file:
      - .env
    networks:
      - main_net
    restart: always
    healthcheck:
      test: ["CMD", "nc", "-zv", "mariadb", "3306"]
      interval: 1s
      timeout: 5s
      retries: 10
  
  nginx:
    image: nginx:1.3.3.7
    container_name: nginx
    build: ./requirements/nginx
    ports:
      - "443:443"
    depends_on:
      - wordpress
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - main_net
    env_file:
        - .env
    restart: always

  wordpress:
    image: wordpress:1.3.3.7
    container_name: wordpress
    build: ./requirements/wordpress
    depends_on:
      - mariadb
    volumes:
      - wordpress:/var/www/wordpress
    env_file:
      - .env
    networks:
      - main_net
    restart: always

  ftp:
    image: ftp:1.3.3.7
    container_name: ftp
    build: ./requirements/ftp
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - main_net
    ports:
      - "21:21"
      - "20:20"
      - "30000-30100:30000-30100"
    env_file:
      - .env
    restart: always
